[2013-04-11 00:05:17] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected 'DB' (T_STRING), expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in /home/felipillo/public_html/test1/app/models/User.php line 107' in /home/felipillo/public_html/test1/app/models/User.php:107
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:06:11] log.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::left_join()' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1369
Stack trace:
#0 /home/felipillo/public_html/test1/app/models/User.php(108): Illuminate\Database\Query\Builder->__call('left_join', Array)
#1 /home/felipillo/public_html/test1/app/models/User.php(108): Illuminate\Database\Query\Builder->left_join('profiles', 'users.id', '=', 'profiles.user_i...')
#2 /home/felipillo/public_html/test1/app/controllers/UserController.php(182): User::perfil()
#3 [internal function]: UserController->getPerfil()
#4 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#5 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#14 {main} [] []
[2013-04-11 00:07:06] log.ERROR: exception 'UnexpectedValueException' with message 'The Response content must be a string or object implementing __toString(), "array" given.' in /home/felipillo/public_html/test1/bootstrap/compiled.php:16124
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(16902): Symfony\Component\HttpFoundation\Response->setContent(Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15932): Illuminate\Http\Response->setContent(Array)
#2 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Array, Object(Illuminate\Http\Request))
#4 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-04-11 00:09:19] log.ERROR: exception 'ErrorException' with message 'Warning: Missing argument 1 for User::perfil(), called in /home/felipillo/public_html/test1/app/controllers/UserController.php on line 182 and defined in /home/felipillo/public_html/test1/app/models/User.php line 105' in /home/felipillo/public_html/test1/app/models/User.php:105
Stack trace:
#0 /home/felipillo/public_html/test1/app/models/User.php(105): Symfony\Component\Debug\ErrorHandler->handle(2, 'Missing argumen...', '/home/felipillo...', 105, Array)
#1 /home/felipillo/public_html/test1/app/controllers/UserController.php(182): User::perfil()
#2 [internal function]: UserController->getPerfil('felipillo')
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#4 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2013-04-11 00:19:08] log.ERROR: exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous (SQL: select `id`, `username`, `email`, `created_at`, `updated_at`, `registro_IP`, `last_IP`, `birthday`, `country_id`, `sexo`, `estado_de_vida_id`, `biografia` from `users` inner join `profiles` on `users`.`id` = `profiles`.`user_id` where `username` = ?) (Bindings: array (
  0 => 'felipillo',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select `id`, `u...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select `id`, `u...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select `id`, `u...', Array)
#3 /home/felipillo/public_html/test1/app/models/User.php(121): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(182): User::perfil('felipillo')
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 00:19:47] log.ERROR: exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in field list is ambiguous (SQL: select `username`, `email`, `created_at`, `updated_at`, `registro_IP`, `last_IP`, `birthday`, `country_id`, `sexo`, `estado_de_vida_id`, `biografia` from `users` inner join `profiles` on `users`.`id` = `profiles`.`user_id` where `username` = ?) (Bindings: array (
  0 => 'felipillo',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select `usernam...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select `usernam...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select `usernam...', Array)
#3 /home/felipillo/public_html/test1/app/models/User.php(120): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(182): User::perfil('felipillo')
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 00:28:06] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Compile Error: Cannot redeclare non static Toddish\Verify\Models\User::$hidden as static User::$hidden in /home/felipillo/public_html/test1/app/models/User.php line 6' in /home/felipillo/public_html/test1/app/models/User.php:6
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:30:01] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Compile Error: Cannot redeclare non static Toddish\Verify\Models\User::$hidden as static User::$hidden in /home/felipillo/public_html/test1/app/models/User.php line 6' in /home/felipillo/public_html/test1/app/models/User.php:6
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:30:58] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Compile Error: Cannot redeclare non static Toddish\Verify\Models\User::$hidden as static User::$hidden in /home/felipillo/public_html/test1/app/models/User.php line 6' in /home/felipillo/public_html/test1/app/models/User.php:6
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:31:59] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Compile Error: Cannot redeclare non static Toddish\Verify\Models\User::$hidden as static User::$hidden in /home/felipillo/public_html/test1/app/models/User.php line 6' in /home/felipillo/public_html/test1/app/models/User.php:6
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:38:08] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Call to a member function toJson() on a non-object in /home/felipillo/public_html/test1/app/controllers/UserController.php line 182' in /home/felipillo/public_html/test1/app/controllers/UserController.php:182
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:49:05] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '$perfil' (T_VARIABLE) in /home/felipillo/public_html/test1/app/controllers/UserController.php line 184' in /home/felipillo/public_html/test1/app/controllers/UserController.php:184
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:49:39] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '$this' (T_VARIABLE) in /home/felipillo/public_html/test1/app/controllers/UserController.php line 184' in /home/felipillo/public_html/test1/app/controllers/UserController.php:184
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:50:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '[', expecting ')' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 184' in /home/felipillo/public_html/test1/app/controllers/UserController.php:184
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:57:11] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '[' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 186' in /home/felipillo/public_html/test1/app/controllers/UserController.php:186
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:59:05] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '[' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 186' in /home/felipillo/public_html/test1/app/controllers/UserController.php:186
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:59:32] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Call to a member function toArray() on a non-object in /home/felipillo/public_html/test1/app/models/User.php line 110' in /home/felipillo/public_html/test1/app/models/User.php:110
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:59:46] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Call to a member function toArray() on a non-object in /home/felipillo/public_html/test1/app/models/User.php line 110' in /home/felipillo/public_html/test1/app/models/User.php:110
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 00:59:56] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Call to a member function toArray() on a non-object in /home/felipillo/public_html/test1/app/models/User.php line 110' in /home/felipillo/public_html/test1/app/models/User.php:110
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 01:00:38] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Call to a member function toArray() on a non-object in /home/felipillo/public_html/test1/app/controllers/UserController.php line 183' in /home/felipillo/public_html/test1/app/controllers/UserController.php:183
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 01:04:46] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined offset: 1 in /home/felipillo/public_html/test1/app/controllers/UserController.php line 210' in /home/felipillo/public_html/test1/app/controllers/UserController.php:210
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(210): Symfony\Component\Debug\ErrorHandler->handle(8, 'Undefined offse...', '/home/felipillo...', 210, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 01:05:23] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined index: id in /home/felipillo/public_html/test1/app/controllers/UserController.php line 210' in /home/felipillo/public_html/test1/app/controllers/UserController.php:210
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(210): Symfony\Component\Debug\ErrorHandler->handle(8, 'Undefined index...', '/home/felipillo...', 210, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 01:05:40] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined index: id in /home/felipillo/public_html/test1/app/controllers/UserController.php line 210' in /home/felipillo/public_html/test1/app/controllers/UserController.php:210
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(210): Symfony\Component\Debug\ErrorHandler->handle(8, 'Undefined index...', '/home/felipillo...', 210, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 01:06:50] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Cannot use object of type stdClass as array in /home/felipillo/public_html/test1/app/controllers/UserController.php line 210' in /home/felipillo/public_html/test1/app/controllers/UserController.php:210
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 01:19:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ')' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 184' in /home/felipillo/public_html/test1/app/controllers/UserController.php:184
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 01:23:14] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/controllers/UserController.php line 197' in /home/felipillo/public_html/test1/app/controllers/UserController.php:197
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(197): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 197, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 01:31:26] log.ERROR: exception 'ErrorException' with message 'Catchable Fatal Error: Argument 1 passed to Illuminate\Database\Grammar::columnize() must be of the type array, string given, called in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 108 and defined in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Grammar.php line 95' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Grammar.php:95
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Grammar.php(95): Symfony\Component\Debug\ErrorHandler->handle(4096, 'Argument 1 pass...', '/home/felipillo...', 95, Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(108): Illuminate\Database\Grammar->columnize('updated_at')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(63): Illuminate\Database\Query\Grammars\Grammar->compileColumns(Object(Illuminate\Database\Query\Builder), 'updated_at')
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php(41): Illuminate\Database\Query\Grammars\Grammar->compileComponents(Object(Illuminate\Database\Query\Builder))
#4 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(823): Illuminate\Database\Query\Grammars\Grammar->compileSelect(Object(Illuminate\Database\Query\Builder))
#5 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Query\Builder->toSql()
#6 /home/felipillo/public_html/test1/app/models/User.php(109): Illuminate\Database\Query\Builder->get('updated_at')
#7 /home/felipillo/public_html/test1/app/controllers/UserController.php(182): User::perfil('felipillo')
#8 [internal function]: UserController->getPerfil('felipillo')
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#10 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []
[2013-04-11 01:31:49] log.ERROR: exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'updated_at' in field list is ambiguous (SQL: select `updated_at` from `users` inner join `profiles` on `users`.`id` = `profiles`.`user_id` where `username` = ?) (Bindings: array (
  0 => 'felipillo',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select `updated...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select `updated...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select `updated...', Array)
#3 /home/felipillo/public_html/test1/app/models/User.php(109): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(182): User::perfil('felipillo')
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 01:33:39] log.ERROR: exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous (SQL: select `id`, `username`, `email`, `created_at`, `updated_at`, `registro_IP`, `last_IP`, `birthday`, `country_id`, `sexo`, `estado_de_vida_id`, `biografia` from `users` inner join `profiles` on `users`.`id` = `profiles`.`user_id` where `username` = ?) (Bindings: array (
  0 => 'felipillo',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select `id`, `u...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select `id`, `u...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select `id`, `u...', Array)
#3 /home/felipillo/public_html/test1/app/models/User.php(109): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(182): User::perfil('felipillo')
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 01:33:56] log.ERROR: exception 'Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in field list is ambiguous (SQL: select `username`, `email`, `created_at`, `updated_at`, `registro_IP`, `last_IP`, `birthday`, `country_id`, `sexo`, `estado_de_vida_id`, `biografia` from `users` inner join `profiles` on `users`.`id` = `profiles`.`user_id` where `username` = ?) (Bindings: array (
  0 => 'felipillo',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select `usernam...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select `usernam...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select `usernam...', Array)
#3 /home/felipillo/public_html/test1/app/models/User.php(109): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(182): User::perfil('felipillo')
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 01:35:18] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '}' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 198' in /home/felipillo/public_html/test1/app/controllers/UserController.php:198
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 02:21:15] log.ERROR: exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'udated_at' in 'field list' (SQL: select `username`, `email`, `registro_IP`, `last_IP`, `birthday`, `country_id`, `sexo`, `estado_de_vida_id`, `biografia`, `created_at`, `udated_at` from `users` inner join `profiles` on `users`.`id` = `profiles`.`user_id` where `username` = ?) (Bindings: array (
  0 => 'felipillo',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select `usernam...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select `usernam...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select `usernam...', Array)
#3 /home/felipillo/public_html/test1/app/models/User.php(119): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(182): User::perfil('felipillo')
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 02:36:54] log.ERROR: exception 'InvalidArgumentException' with message 'View [users.perfil] not found.' in /home/felipillo/public_html/test1/bootstrap/compiled.php:13810
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(13764): Illuminate\View\FileViewFinder->findInPaths('users.perfil', Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(13991): Illuminate\View\FileViewFinder->find('users.perfil')
#2 /home/felipillo/public_html/test1/bootstrap/compiled.php(4257): Illuminate\View\Environment->make('users.perfil', Array)
#3 /home/felipillo/public_html/test1/app/controllers/UserController.php(189): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(189): Illuminate\Support\Facades\View::make('users.perfil', Array)
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 02:37:23] log.ERROR: exception 'InvalidArgumentException' with message 'View [users.perfil] not found.' in /home/felipillo/public_html/test1/bootstrap/compiled.php:13810
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(13764): Illuminate\View\FileViewFinder->findInPaths('users.perfil', Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(13991): Illuminate\View\FileViewFinder->find('users.perfil')
#2 /home/felipillo/public_html/test1/bootstrap/compiled.php(4257): Illuminate\View\Environment->make('users.perfil', Array)
#3 /home/felipillo/public_html/test1/app/controllers/UserController.php(189): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(189): Illuminate\Support\Facades\View::make('users.perfil', Array)
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 02:37:26] log.ERROR: exception 'InvalidArgumentException' with message 'View [users.perfil] not found.' in /home/felipillo/public_html/test1/bootstrap/compiled.php:13810
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(13764): Illuminate\View\FileViewFinder->findInPaths('users.perfil', Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(13991): Illuminate\View\FileViewFinder->find('users.perfil')
#2 /home/felipillo/public_html/test1/bootstrap/compiled.php(4257): Illuminate\View\Environment->make('users.perfil', Array)
#3 /home/felipillo/public_html/test1/app/controllers/UserController.php(189): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(189): Illuminate\Support\Facades\View::make('users.perfil', Array)
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 02:37:51] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 3' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:3
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(3): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 3, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15845): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15609): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15592): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16900): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15932): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 02:40:23] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined variable: user in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 3' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:3
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(3): Symfony\Component\Debug\ErrorHandler->handle(8, 'Undefined varia...', '/home/felipillo...', 3, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15845): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15609): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15592): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16900): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15932): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 02:45:06] log.ERROR: exception 'ErrorException' with message 'Notice: Array to string conversion in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 8' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:8
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(8): Symfony\Component\Debug\ErrorHandler->handle(8, 'Array to string...', '/home/felipillo...', 8, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15845): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15609): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15592): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16900): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15932): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 02:45:28] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 8' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:8
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(8): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 8, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15845): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15609): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15592): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16900): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15932): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 03:37:05] log.ERROR: exception 'ErrorException' with message 'Runtime Notice: Non-static method User::getUsernameID() should not be called statically, assuming $this from incompatible context in /home/felipillo/public_html/test1/app/controllers/UserController.php line 185' in /home/felipillo/public_html/test1/app/controllers/UserController.php:185
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(185): Symfony\Component\Debug\ErrorHandler->handle(2048, 'Non-static meth...', '/home/felipillo...', 185, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 03:39:28] log.ERROR: exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'where clause' (SQL: select `id` from `users` where `name` = ? limit 1) (Bindings: array (
  0 => 'felipillo',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select `id` fro...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select `id` fro...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select `id` fro...', Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(859): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(846): Illuminate\Database\Query\Builder->first(Array)
#5 /home/felipillo/public_html/test1/app/models/User.php(32): Illuminate\Database\Query\Builder->pluck('id')
#6 /home/felipillo/public_html/test1/app/controllers/UserController.php(185): User::getUsernameID('felipillo')
#7 [internal function]: UserController->getPerfil('felipillo')
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 03:47:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '$username' (T_VARIABLE) in /home/felipillo/public_html/test1/app/controllers/UserController.php line 186' in /home/felipillo/public_html/test1/app/controllers/UserController.php:186
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 03:47:30] log.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::profile()' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1369
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('profile', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->profile()
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(490): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/app/controllers/UserController.php(187): Illuminate\Database\Eloquent\Builder->__call('profile', Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(187): Illuminate\Database\Eloquent\Builder->profile()
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 03:48:34] log.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::profile()' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1369
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('profile', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->profile()
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(490): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/app/controllers/UserController.php(187): Illuminate\Database\Eloquent\Builder->__call('profile', Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(187): Illuminate\Database\Eloquent\Builder->profile()
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 03:52:55] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Compile Error: Cannot redeclare non static Illuminate\Database\Eloquent\Model::$timestamps as static Profile::$timestamps in /home/felipillo/public_html/test1/app/models/Profile.php line 16' in /home/felipillo/public_html/test1/app/models/Profile.php:16
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 03:55:53] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/controllers/UserController.php line 187' in /home/felipillo/public_html/test1/app/controllers/UserController.php:187
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(187): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 187, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 04:01:01] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/controllers/UserController.php line 208' in /home/felipillo/public_html/test1/app/controllers/UserController.php:208
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(208): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 208, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 04:02:19] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 12' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:12
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(12): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 12, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15845): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15609): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15592): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16900): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15932): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 04:02:51] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected 'endforeach' (T_ENDFOREACH) in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 12' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:12
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 04:03:35] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 11' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:11
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(11): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 11, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15845): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15609): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15592): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16900): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15932): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 04:04:25] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined index: username in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 11' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:11
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(11): Symfony\Component\Debug\ErrorHandler->handle(8, 'Undefined index...', '/home/felipillo...', 11, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15845): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15609): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15592): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16900): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15932): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 04:05:37] log.ERROR: exception 'ErrorException' with message 'Notice: Array to string conversion in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 11' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:11
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(11): Symfony\Component\Debug\ErrorHandler->handle(8, 'Array to string...', '/home/felipillo...', 11, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15845): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15609): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15592): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16900): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15932): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13320): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13299): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 04:06:36] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '}' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 214' in /home/felipillo/public_html/test1/app/controllers/UserController.php:214
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 05:28:41] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected end of file in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 22' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:22
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 05:29:57] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected end of file in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 22' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:22
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 05:32:09] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined variable: user in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 11' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:11
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(11): Symfony\Component\Debug\ErrorHandler->handle(8, 'Undefined varia...', '/home/felipillo...', 11, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15886): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15650): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15633): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16941): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15973): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 05:40:41] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected 'return' (T_RETURN) in /home/felipillo/public_html/test1/app/controllers/UserController.php line 212' in /home/felipillo/public_html/test1/app/controllers/UserController.php:212
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 05:41:01] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected 'return' (T_RETURN) in /home/felipillo/public_html/test1/app/controllers/UserController.php line 212' in /home/felipillo/public_html/test1/app/controllers/UserController.php:212
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 05:41:29] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected 'return' (T_RETURN) in /home/felipillo/public_html/test1/app/controllers/UserController.php line 212' in /home/felipillo/public_html/test1/app/controllers/UserController.php:212
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 05:42:53] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected 'return' (T_RETURN) in /home/felipillo/public_html/test1/app/controllers/UserController.php line 212' in /home/felipillo/public_html/test1/app/controllers/UserController.php:212
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 05:43:28] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined variable: user in /home/felipillo/public_html/test1/app/controllers/UserController.php line 207' in /home/felipillo/public_html/test1/app/controllers/UserController.php:207
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(207): Symfony\Component\Debug\ErrorHandler->handle(8, 'Undefined varia...', '/home/felipillo...', 207, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 05:47:21] log.ERROR: exception 'ErrorException' with message 'Runtime Notice: Non-static method User::date() should not be called statically, assuming $this from incompatible context in /home/felipillo/public_html/test1/app/controllers/UserController.php line 207' in /home/felipillo/public_html/test1/app/controllers/UserController.php:207
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(207): Symfony\Component\Debug\ErrorHandler->handle(2048, 'Non-static meth...', '/home/felipillo...', 207, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 05:50:06] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Call to a member function date() on a non-object in /home/felipillo/public_html/test1/app/controllers/UserController.php line 207' in /home/felipillo/public_html/test1/app/controllers/UserController.php:207
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 05:54:11] log.ERROR: exception 'ErrorException' with message 'Runtime Notice: Non-static method User::profile() should not be called statically, assuming $this from incompatible context in /home/felipillo/public_html/test1/app/controllers/UserController.php line 205' in /home/felipillo/public_html/test1/app/controllers/UserController.php:205
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(205): Symfony\Component\Debug\ErrorHandler->handle(2048, 'Non-static meth...', '/home/felipillo...', 205, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 05:54:48] log.ERROR: exception 'ErrorException' with message 'Runtime Notice: Non-static method User::profile() should not be called statically, assuming $this from incompatible context in /home/felipillo/public_html/test1/app/controllers/UserController.php line 205' in /home/felipillo/public_html/test1/app/controllers/UserController.php:205
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(205): Symfony\Component\Debug\ErrorHandler->handle(2048, 'Non-static meth...', '/home/felipillo...', 205, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 05:57:29] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '=' in /home/felipillo/public_html/test1/app/models/User.php line 32' in /home/felipillo/public_html/test1/app/models/User.php:32
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 05:57:48] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined variable: user in /home/felipillo/public_html/test1/app/controllers/UserController.php line 206' in /home/felipillo/public_html/test1/app/controllers/UserController.php:206
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(206): Symfony\Component\Debug\ErrorHandler->handle(8, 'Undefined varia...', '/home/felipillo...', 206, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 06:01:36] log.ERROR: exception 'ErrorException' with message 'Notice: Use of undefined constant users - assumed 'users' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 207' in /home/felipillo/public_html/test1/app/controllers/UserController.php:207
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(207): Symfony\Component\Debug\ErrorHandler->handle(8, 'Use of undefine...', '/home/felipillo...', 207, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 06:02:31] log.ERROR: exception 'ErrorException' with message 'Notice: Use of undefined constant users - assumed 'users' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 207' in /home/felipillo/public_html/test1/app/controllers/UserController.php:207
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(207): Symfony\Component\Debug\ErrorHandler->handle(8, 'Use of undefine...', '/home/felipillo...', 207, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 06:03:26] log.ERROR: exception 'ErrorException' with message 'Notice: Use of undefined constant users - assumed 'users' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 207' in /home/felipillo/public_html/test1/app/controllers/UserController.php:207
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(207): Symfony\Component\Debug\ErrorHandler->handle(8, 'Use of undefine...', '/home/felipillo...', 207, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 06:04:35] log.ERROR: exception 'ErrorException' with message 'Notice: Use of undefined constant users - assumed 'users' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 207' in /home/felipillo/public_html/test1/app/controllers/UserController.php:207
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(207): Symfony\Component\Debug\ErrorHandler->handle(8, 'Use of undefine...', '/home/felipillo...', 207, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 06:04:39] log.ERROR: exception 'ErrorException' with message 'Notice: Use of undefined constant users - assumed 'users' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 207' in /home/felipillo/public_html/test1/app/controllers/UserController.php:207
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(207): Symfony\Component\Debug\ErrorHandler->handle(8, 'Use of undefine...', '/home/felipillo...', 207, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 06:05:20] log.ERROR: exception 'ErrorException' with message 'Notice: Use of undefined constant users - assumed 'users' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 207' in /home/felipillo/public_html/test1/app/controllers/UserController.php:207
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(207): Symfony\Component\Debug\ErrorHandler->handle(8, 'Use of undefine...', '/home/felipillo...', 207, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 06:06:30] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected 'return' (T_RETURN) in /home/felipillo/public_html/test1/app/controllers/UserController.php line 208' in /home/felipillo/public_html/test1/app/controllers/UserController.php:208
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 06:06:44] log.ERROR: exception 'ErrorException' with message 'Notice: Use of undefined constant users - assumed 'users' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 208' in /home/felipillo/public_html/test1/app/controllers/UserController.php:208
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(208): Symfony\Component\Debug\ErrorHandler->handle(8, 'Use of undefine...', '/home/felipillo...', 208, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 06:08:09] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '}' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 218' in /home/felipillo/public_html/test1/app/controllers/UserController.php:218
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 06:08:22] log.ERROR: exception 'ErrorException' with message 'Notice: Use of undefined constant users - assumed 'users' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 207' in /home/felipillo/public_html/test1/app/controllers/UserController.php:207
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(207): Symfony\Component\Debug\ErrorHandler->handle(8, 'Use of undefine...', '/home/felipillo...', 207, Array)
#1 [internal function]: UserController->getPerfil('felipillo')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 06:09:58] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 14' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:14
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(14): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 14, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15886): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15650): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15633): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16941): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15973): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 06:10:19] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 14' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:14
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(14): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 14, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15886): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15650): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15633): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16941): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15973): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 06:10:23] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 14' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:14
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(14): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 14, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15886): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15650): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15633): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16941): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15973): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 06:10:57] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 14' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:14
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(14): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 14, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15886): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15650): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15633): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16941): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15973): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 06:12:31] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Call to a member function date() on a non-object in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 14' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:14
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 06:18:45] log.ERROR: exception 'ErrorException' with message 'Runtime Notice: Non-static method User::profile() should not be called statically, assuming $this from incompatible context in /home/felipillo/public_html/test1/app/controllers/UserController.php line 205' in /home/felipillo/public_html/test1/app/controllers/UserController.php:205
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(205): Symfony\Component\Debug\ErrorHandler->handle(2048, 'Non-static meth...', '/home/felipillo...', 205, Array)
#1 [internal function]: UserController->getPerfil()
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 06:19:27] log.ERROR: exception 'ErrorException' with message 'Runtime Notice: Non-static method User::profile() should not be called statically, assuming $this from incompatible context in /home/felipillo/public_html/test1/app/controllers/UserController.php line 205' in /home/felipillo/public_html/test1/app/controllers/UserController.php:205
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(205): Symfony\Component\Debug\ErrorHandler->handle(2048, 'Non-static meth...', '/home/felipillo...', 205, Array)
#1 [internal function]: UserController->getPerfil()
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 06:21:45] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Using $this when not in object context in /home/felipillo/public_html/test1/app/models/User.php line 20' in /home/felipillo/public_html/test1/app/models/User.php:20
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 06:25:54] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Compile Error: Cannot redeclare non static Illuminate\Database\Eloquent\Model::$timestamps as static Profile::$timestamps in /home/felipillo/public_html/test1/app/models/Profile.php line 16' in /home/felipillo/public_html/test1/app/models/Profile.php:16
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 06:28:46] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Call to a member function profile() on a non-object in /home/felipillo/public_html/test1/app/controllers/UserController.php line 207' in /home/felipillo/public_html/test1/app/controllers/UserController.php:207
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 06:34:09] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined property: stdClass::$first_name in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 14' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:14
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(14): Symfony\Component\Debug\ErrorHandler->handle(8, 'Undefined prope...', '/home/felipillo...', 14, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15886): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15650): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15633): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16941): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15973): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 06:34:48] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined property: stdClass::$user_name in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 14' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:14
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(14): Symfony\Component\Debug\ErrorHandler->handle(8, 'Undefined prope...', '/home/felipillo...', 14, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15886): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15650): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15633): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16941): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15973): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 06:37:35] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 18' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:18
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(18): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 18, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15886): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15650): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15633): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16941): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15973): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 06:39:07] log.ERROR: exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'first_name' in 'field list' (SQL: select `username`, `first_name`, `last_name`, `email`, `birthday`, `country_id`, `sexo`, `estado_de_vida_id`, `biografia`, `avtar_file_name`, `created_at`, `updated_at` from `users` inner join `profiles` on `users`.`id` = `profiles`.`user_id` where `username` = ?) (Bindings: array (
  0 => 'felipillo',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select `usernam...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select `usernam...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select `usernam...', Array)
#3 /home/felipillo/public_html/test1/app/models/User.php(147): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(184): User::perfil('felipillo')
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 06:39:17] log.ERROR: exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'first_name' in 'field list' (SQL: select `username`, `first_name`, `last_name`, `email`, `birthday`, `country_id`, `sexo`, `estado_de_vida_id`, `biografia`, `avtar_file_name`, `created_at`, `updated_at` from `users` inner join `profiles` on `users`.`id` = `profiles`.`user_id` where `username` = ?) (Bindings: array (
  0 => 'felipillo',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select `usernam...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select `usernam...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select `usernam...', Array)
#3 /home/felipillo/public_html/test1/app/models/User.php(147): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/app/controllers/UserController.php(184): User::perfil('felipillo')
#5 [internal function]: UserController->getPerfil('felipillo')
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('felipillo')
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#16 {main} [] []
[2013-04-11 06:55:11] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected ''password'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /home/felipillo/public_html/test1/app/models/User.php line 11' in /home/felipillo/public_html/test1/app/models/User.php:11
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 07:05:26] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Call to undefined method stdClass::date() in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 14' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:14
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 07:05:37] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Call to undefined method stdClass::date() in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 14' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:14
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 07:22:19] log.ERROR: exception 'ErrorException' with message 'Notice: Undefined property: stdClass::$pais in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8 line 22' in /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8:22
Stack trace:
#0 /home/felipillo/public_html/test1/app/storage/views/42d69382b25fdf00f7a98b3b181f73f8(22): Symfony\Component\Debug\ErrorHandler->handle(8, 'Undefined prope...', '/home/felipillo...', 22, Array)
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(15886): include('/home/felipillo...')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/felipillo...', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(15650): Illuminate\View\Engines\CompilerEngine->get('/home/felipillo...', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(15633): Illuminate\View\View->getContents()
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(16941): Illuminate\View\View->render()
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(15973): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7392): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getPerfil', Object(Illuminate\View\View))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('pancho')
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 07:31:32] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected ')' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 186' in /home/felipillo/public_html/test1/app/controllers/UserController.php:186
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 07:31:47] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected ')' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 186' in /home/felipillo/public_html/test1/app/controllers/UserController.php:186
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 07:32:22] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected ')' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 186' in /home/felipillo/public_html/test1/app/controllers/UserController.php:186
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 21:05:52] log.ERROR: exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: select * from `paises` where `id` = ? limit 1) (Bindings: array (
  0 => 'mx',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select * from `...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select * from `...', Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(207): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(96): Illuminate\Database\Eloquent\Builder->getModels(Array)
#5 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(72): Illuminate\Database\Eloquent\Builder->get(Array)
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(61): Illuminate\Database\Eloquent\Builder->first(Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(8384): Illuminate\Database\Eloquent\Builder->find('mx', Array)
#8 /home/felipillo/public_html/test1/app/controllers/UserController.php(189): Illuminate\Database\Eloquent\Model::find('mx')
#9 [internal function]: UserController->getPerfil('Pancho')
#10 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#11 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('Pancho')
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#18 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#19 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#20 {main} [] []
[2013-04-11 21:06:51] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected ''mx'' (T_CONSTANT_ENCAPSED_STRING) in /home/felipillo/public_html/test1/app/controllers/UserController.php line 189' in /home/felipillo/public_html/test1/app/controllers/UserController.php:189
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 21:18:11] log.ERROR: exception 'ErrorException' with message 'Notice: Trying to get property of non-object in /home/felipillo/public_html/test1/app/controllers/UserController.php line 188' in /home/felipillo/public_html/test1/app/controllers/UserController.php:188
Stack trace:
#0 /home/felipillo/public_html/test1/app/controllers/UserController.php(188): Symfony\Component\Debug\ErrorHandler->handle(8, 'Trying to get p...', '/home/felipillo...', 188, Array)
#1 [internal function]: UserController->getPerfil('Pancho')
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getPerfil', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getPerfil', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('Pancho')
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2013-04-11 22:31:09] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '}' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 177' in /home/felipillo/public_html/test1/app/controllers/UserController.php:177
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 22:31:45] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '}' in /home/felipillo/public_html/test1/app/controllers/UserController.php line 192' in /home/felipillo/public_html/test1/app/controllers/UserController.php:192
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 22:32:02] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php:290
Stack trace:
#0 [internal function]: Illuminate\Routing\Controllers\Controller->missingMethod(Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('missingMethod', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(7079): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'missingMethod', Array)
#4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Array)
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(13361): call_user_func_array(Object(Closure), Array)
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13340): Illuminate\Routing\Route->callCallable()
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7099): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2013-04-11 22:45:07] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting '{' in /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php line 153' in /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php:153
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 22:49:54] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected '\' (T_NS_SEPARATOR), expecting '{' in /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php line 153' in /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php:153
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 22:50:33] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected 'Exception' (T_STRING), expecting '{' in /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php line 153' in /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php:153
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 22:51:29] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Error: Class 'Toddish\Verify\Exception' not found in /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php line 148' in /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php:148
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4014): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 22:52:15] log.ERROR: exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'where clause' (SQL: select count(*) as aggregate from `users` where `username` = ? and `0` is null) (Bindings: array (
  0 => 'djv0022@gmail.com',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select count(*)...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1091): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1033): Illuminate\Database\Query\Builder->aggregate('count', Array)
#5 [internal function]: Illuminate\Database\Query\Builder->count()
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(490): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php(75): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#8 /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php(75): Illuminate\Database\Eloquent\Builder->count()
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(243): Toddish\Verify\VerifyUserProvider->retrieveByCredentials(Array)
#10 [internal function]: Illuminate\Auth\Guard->attempt(Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(10935): call_user_func_array(Array, Array)
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(4339): Illuminate\Support\Manager->__call('attempt', Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(4339): Illuminate\Auth\AuthManager->attempt(Array)
#14 /home/felipillo/public_html/test1/app/controllers/UserController.php(171): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#15 /home/felipillo/public_html/test1/app/controllers/UserController.php(171): Illuminate\Support\Facades\Auth::attempt(Array)
#16 [internal function]: UserController->postEntrar()
#17 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#18 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postEntrar', Array)
#19 /home/felipillo/public_html/test1/bootstrap/compiled.php(7163): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postEntrar', Array)
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#21 /home/felipillo/public_html/test1/bootstrap/compiled.php(13445): call_user_func_array(Object(Closure), Array)
#22 /home/felipillo/public_html/test1/bootstrap/compiled.php(13424): Illuminate\Routing\Route->callCallable()
#23 /home/felipillo/public_html/test1/bootstrap/compiled.php(7183): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#24 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#26 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#27 {main} [] []
[2013-04-11 22:54:03] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/felipillo/public_html/test1/bootstrap/compiled.php:7489
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(7206): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 /home/felipillo/public_html/test1/bootstrap/compiled.php(7182): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2013-04-11 22:55:50] log.ERROR: exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column '0' in 'where clause' (SQL: select count(*) as aggregate from `users` where `username` = ? and `0` is null) (Bindings: array (
  0 => 'djv0022@gmail.com',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select count(*)...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1091): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1033): Illuminate\Database\Query\Builder->aggregate('count', Array)
#5 [internal function]: Illuminate\Database\Query\Builder->count()
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(490): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php(75): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#8 /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php(75): Illuminate\Database\Eloquent\Builder->count()
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(243): Toddish\Verify\VerifyUserProvider->retrieveByCredentials(Array)
#10 [internal function]: Illuminate\Auth\Guard->attempt(Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(10935): call_user_func_array(Array, Array)
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(4339): Illuminate\Support\Manager->__call('attempt', Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(4339): Illuminate\Auth\AuthManager->attempt(Array)
#14 /home/felipillo/public_html/test1/app/controllers/UserController.php(171): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#15 /home/felipillo/public_html/test1/app/controllers/UserController.php(171): Illuminate\Support\Facades\Auth::attempt(Array)
#16 [internal function]: UserController->postEntrar()
#17 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#18 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postEntrar', Array)
#19 /home/felipillo/public_html/test1/bootstrap/compiled.php(7163): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postEntrar', Array)
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#21 /home/felipillo/public_html/test1/bootstrap/compiled.php(13445): call_user_func_array(Object(Closure), Array)
#22 /home/felipillo/public_html/test1/bootstrap/compiled.php(13424): Illuminate\Routing\Route->callCallable()
#23 /home/felipillo/public_html/test1/bootstrap/compiled.php(7183): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#24 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#26 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#27 {main} [] []
[2013-04-11 23:02:17] log.ERROR: exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rememberMe' in 'where clause' (SQL: select count(*) as aggregate from `users` where `email` = ? and `rememberMe` is null) (Bindings: array (
  0 => 'djv0022@gmail.com',
))' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php:494
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(467): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select count(*)...', Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Connection.php(261): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(880): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1091): Illuminate\Database\Query\Builder->get(Array)
#4 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1033): Illuminate\Database\Query\Builder->aggregate('count', Array)
#5 [internal function]: Illuminate\Database\Query\Builder->count()
#6 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(490): call_user_func_array(Array, Array)
#7 /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php(95): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#8 /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php(95): Illuminate\Database\Eloquent\Builder->count()
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(243): Toddish\Verify\VerifyUserProvider->retrieveByCredentials(Array)
#10 [internal function]: Illuminate\Auth\Guard->attempt(Array)
#11 /home/felipillo/public_html/test1/bootstrap/compiled.php(10935): call_user_func_array(Array, Array)
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(4339): Illuminate\Support\Manager->__call('attempt', Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(4339): Illuminate\Auth\AuthManager->attempt(Array)
#14 /home/felipillo/public_html/test1/app/controllers/UserController.php(171): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#15 /home/felipillo/public_html/test1/app/controllers/UserController.php(171): Illuminate\Support\Facades\Auth::attempt(Array)
#16 [internal function]: UserController->postEntrar()
#17 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#18 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postEntrar', Array)
#19 /home/felipillo/public_html/test1/bootstrap/compiled.php(7163): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postEntrar', Array)
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#21 /home/felipillo/public_html/test1/bootstrap/compiled.php(13445): call_user_func_array(Object(Closure), Array)
#22 /home/felipillo/public_html/test1/bootstrap/compiled.php(13424): Illuminate\Routing\Route->callCallable()
#23 /home/felipillo/public_html/test1/bootstrap/compiled.php(7183): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#24 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#26 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#27 {main} [] []
[2013-04-11 23:30:31] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Parse: syntax error, unexpected 'return' (T_RETURN) in /home/felipillo/public_html/test1/app/controllers/UserController.php line 224' in /home/felipillo/public_html/test1/app/controllers/UserController.php:224
Stack trace:
#0 /home/felipillo/public_html/test1/bootstrap/compiled.php(4018): Symfony\Component\Debug\ErrorHandler->handleFatal()
#1 [internal function]: Illuminate\Exception\ExceptionServiceProvider->Illuminate\Exception\{closure}()
#2 {main} [] []
[2013-04-11 23:33:44] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php:290
Stack trace:
#0 [internal function]: Illuminate\Routing\Controllers\Controller->missingMethod(Array)
#1 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#2 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('missingMethod', Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(7163): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'missingMethod', Array)
#4 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Array)
#5 /home/felipillo/public_html/test1/bootstrap/compiled.php(13445): call_user_func_array(Object(Closure), Array)
#6 /home/felipillo/public_html/test1/bootstrap/compiled.php(13424): Illuminate\Routing\Route->callCallable()
#7 /home/felipillo/public_html/test1/bootstrap/compiled.php(7183): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#8 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#9 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#10 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []
[2013-04-11 23:34:47] log.ERROR: exception 'Toddish\Verify\UserUnverifiedException' with message 'User is unverified' in /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php:119
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(250): Toddish\Verify\VerifyUserProvider->validateCredentials(Object(User), Array)
#1 [internal function]: Illuminate\Auth\Guard->attempt(Array, NULL)
#2 /home/felipillo/public_html/test1/bootstrap/compiled.php(10935): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(4341): Illuminate\Support\Manager->__call('attempt', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(4341): Illuminate\Auth\AuthManager->attempt(Array, NULL)
#5 /home/felipillo/public_html/test1/app/controllers/UserController.php(170): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#6 /home/felipillo/public_html/test1/app/controllers/UserController.php(170): Illuminate\Support\Facades\Auth::attempt(Array, NULL)
#7 [internal function]: UserController->postEntrar()
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postEntrar', Array)
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7163): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postEntrar', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13445): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13424): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7183): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 23:36:08] log.ERROR: exception 'Toddish\Verify\UserUnverifiedException' with message 'User is unverified' in /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php:119
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(250): Toddish\Verify\VerifyUserProvider->validateCredentials(Object(User), Array)
#1 [internal function]: Illuminate\Auth\Guard->attempt(Array, NULL)
#2 /home/felipillo/public_html/test1/bootstrap/compiled.php(10935): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(4341): Illuminate\Support\Manager->__call('attempt', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(4341): Illuminate\Auth\AuthManager->attempt(Array, NULL)
#5 /home/felipillo/public_html/test1/app/controllers/UserController.php(170): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#6 /home/felipillo/public_html/test1/app/controllers/UserController.php(170): Illuminate\Support\Facades\Auth::attempt(Array, NULL)
#7 [internal function]: UserController->postEntrar()
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postEntrar', Array)
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7163): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postEntrar', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13445): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13424): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7183): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
[2013-04-11 23:53:27] log.ERROR: exception 'Toddish\Verify\UserUnverifiedException' with message 'User is unverified' in /home/felipillo/public_html/test1/vendor/toddish/verify/src/Toddish/Verify/VerifyUserProvider.php:119
Stack trace:
#0 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Auth/Guard.php(250): Toddish\Verify\VerifyUserProvider->validateCredentials(Object(User), Array)
#1 [internal function]: Illuminate\Auth\Guard->attempt(Array, NULL)
#2 /home/felipillo/public_html/test1/bootstrap/compiled.php(10935): call_user_func_array(Array, Array)
#3 /home/felipillo/public_html/test1/bootstrap/compiled.php(4341): Illuminate\Support\Manager->__call('attempt', Array)
#4 /home/felipillo/public_html/test1/bootstrap/compiled.php(4341): Illuminate\Auth\AuthManager->attempt(Array, NULL)
#5 /home/felipillo/public_html/test1/app/controllers/UserController.php(170): Illuminate\Support\Facades\Facade::__callStatic('attempt', Array)
#6 /home/felipillo/public_html/test1/app/controllers/UserController.php(170): Illuminate\Support\Facades\Auth::attempt(Array, NULL)
#7 [internal function]: UserController->postEntrar()
#8 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array)
#9 /home/felipillo/public_html/test1/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postEntrar', Array)
#10 /home/felipillo/public_html/test1/bootstrap/compiled.php(7163): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postEntrar', Array)
#11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#12 /home/felipillo/public_html/test1/bootstrap/compiled.php(13445): call_user_func_array(Object(Closure), Array)
#13 /home/felipillo/public_html/test1/bootstrap/compiled.php(13424): Illuminate\Routing\Route->callCallable()
#14 /home/felipillo/public_html/test1/bootstrap/compiled.php(7183): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 /home/felipillo/public_html/test1/bootstrap/compiled.php(958): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 /home/felipillo/public_html/test1/bootstrap/compiled.php(946): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#17 /home/felipillo/public_html/test1/public/index.php(49): Illuminate\Foundation\Application->run()
#18 {main} [] []
